### ISSUE TITLE
extruder skipping steps

### ISSUE THREAD

**Issue by MKdent** [ZONESTAR3D/Upgrade-kit-guide#1]
Hi, I do have the Z9v5_E4 board. After changing to direct drive update the extruder skips steps, for example if you do load filament fast...
Any adjustment in marlin conceringing this?

**Comment by ZONESTAR3D** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Dear,
        Thanks contact with us.You can change the steps/mm of extruder to correct it.1. If you have a ZONESTAR 3D printer, please tell me the model of your printer, I will provide the correct firmware to you.2. If you use this control board to your own 3d printer, please tell me more details  (as below) , I will tell you how to set the steps/mm of extruder.2-1. Extruder type :(for example Titan, BGM, etc.)2-2 Motor driver (A4988, TMC220x, TMC2225/6, etc.)Here is the setting in marlin source code (configuration.h):
    
        
            
        
    
    
     
    
        
            ZONESTAR online shopZONESTAR Innovations Tech., Ltd.
                                  ***@***.*** email: ***@***.***

        
    
 

    On 3/6/2022 ***@***.***> wrote： 



Hi, I do have the Z9v5_E4 board. After changing to direct drive update the extruder skips steps, for example if you do load filament fast...
Any adjustment in marlin conceringing this?

**Comment by MKdent** [comment]
Hi, 
I do have 

Z9V5 Pro version 2 (probably  ZM3E4 board...with exturder stepper driver A4988.).

I uploaded firmware Z9V5_E4 and defined BMG Extruder. So steps/mm , I believe, are actually adjusted right....

I did also manually changed them over display. And same thing happenend. loading filament fast and motor skips steps.

So I believe motor has not enough torque?
Are there any adjustements to be made for stepper driver current?

**Comment by ZONESTAR3D** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hi Friend,
        I think your printer model is Z9V5Pro-MK2, you can refer to the below link to know more details of these model.https://github.com/ZONESTAR3D/Z9/tree/main/Z9V5 Firmware Download link for Z9V5Pro-MK2:https://github.com/ZONESTAR3D/Firmware/tree/master/Z9/Z9V5/bin/Z9V5Pro/released 
    
        
            
        
    
    
     
    
        
            ZONESTAR online shopZONESTAR Innovations Tech., Ltd.
                                  ***@***.*** email: ***@***.***

        
    
 

    On 3/8/2022 ***@***.***> wrote： 




    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Dear,
        Thanks contact with us.You can change the steps/mm of extruder to correct it.1. If you have a ZONESTAR 3D printer, please tell me the model of your printer, I will provide the correct firmware to you.2. If you use this control board to your own 3d printer, please tell me more details  (as below) , I will tell you how to set the steps/mm of extruder.2-1. Extruder type :(for example Titan, BGM, etc.)2-2 Motor driver (A4988, TMC220x, TMC2225/6, etc.)Here is the setting in marlin source code (configuration.h):
    
        
            
        
    
    
     
    
        
            ZONESTAR online shopZONESTAR Innovations Tech., Ltd.
                                  ***@***.*** email: ***@***.***

        
    
 

    On 3/6/2022 ***@***.***> wrote： 



Hi, I do have the Z9v5_E4 board. After changing to direct drive update the extruder skips steps, for example if you do load filament fast...
Any adjustment in marlin conceringing this?

**Comment by MKdent** [comment]
Thanks for helping! I tried your firmware but it's the same. It feels like the extruder motor has not enough torque or power...

**Comment by ZONESTAR3D** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hi Friend,
        Please take a photo to me about the serial number of your kit, you can find a white label pasted on the power supply.And please take a photo to show the firmware version too: LCD MENU>>Info>>I will help to check.PS: If possible, please take a small video to show what's question you have and send it to me.
    
        
            
        
    
    
     
    
        
            ZONESTAR online shopZONESTAR Innovations Tech., Ltd.
                                  ***@***.*** email: ***@***.***

        
    
 

    On 3/8/2022 ***@***.***> wrote： 



Hi,
I do have
Z9V5 Pro version 2 (probably  ZM3E4 board...with exturder stepper driver A4988.).
I uploaded firmware Z9V5_E4 and defined BMG Extruder. So steps/mm , I believe, are actually adjusted right....
I did also manually changed them over display. And same thing happenend. loading filament fast and motor skips steps.
So I believe motor has not enough torque?
Are there any adjustements to be made for stepper driver current?

**Comment by MKdent** [comment]
Hi, 
you find the pictures of firmware and versions below.
I uploaded a video. Hope you can see it. https://youtu.be/1vfw2IVoRfE
The extruder is working fine when  slow motion is required. But when it should load filament fast the stepper motor is not powerful enough and cannot move the white gear ( See menu prepare->filament->laod quickly). I think it also has an negativ  effect on normal printing.

Hope you know a solution.


![IMG_20220310_204832 1](https://user-images.githubusercontent.com/13108176/157746177-6e3df637-8d7b-4214-a1a2-63c435e6c0a3.jpg)
![IMG_20220310_204854 1](https://user-images.githubusercontent.com/13108176/157746253-40bbaeb5-8004-42bc-9b44-c7811d4aeef9.jpg)
![IMG_20220310_204925 1](https://user-images.githubusercontent.com/13108176/157746332-5ad6f699-62ea-460d-88aa-d1aeccb5390c.jpg)

**Comment by ZONESTAR3D** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hi,
        1. please note "Quickly Load" only work when loading filament from the extruder to the hotend, it should not be used when filaments have entered the hot end.2. please follow this link to check if the extruders installed well and try to increase the pressure of the extrudee by adjust the srews.
    
        
            
        
    
    
     
    
        
            ZONESTAR online shopZONESTAR Innovations Tech., Ltd.
                                  ***@***.*** email: ***@***.***

        
    
 

    On 3/11/2022 ***@***.***> wrote： 



Hi,
you find the pictures of firmware and versions below.
I uploaded a video. Hope you can see it. https://youtu.be/1vfw2IVoRfE
The extruder is working fine when  slow motion is required. But when it should load filament fast the stepper motor is not powerful enough and cannot move the white gear ( See menu prepare->filament->laod quickly). I think it also has an negativ  effect on normal printing.
Hope you know a solution.

**Comment by MKdent** [comment]
"Quickly Load" only work when loading filament from the extruder to the hotend, it should not be used when filaments have entered the hot end.

I wasn't aware of that. So kept on going and I was able to print.  Thanks for the info.
Meanwhile another problem occured for which I opend another issue. Maybe you have a look at this.
