### ISSUE TITLE
Without active bed leveling, printing is fine but when it comes to active bed leveling strange movement.....

### ISSUE THREAD

**Issue by MKdent** [ZONESTAR3D/Upgrade-kit-guide#2]
Another problem occured with the zl-sensor. Bed leveling does work fine but when it comes to printing with active bed leveling (M420 S1) the extruder shifts x and y position somehow.  It's printing like concentric circles ( at the beginnin when the brim should be printed) and even prints outside the bed. I'm using the normal firmware source code but do activate active bed leveling with M420 S1. 

This is my cura start code:

G28 ; home all axes
G29
M500
M420 S1
G1 Z5 F3000 ; lift
G1 X5 Y10 F1500 ; move to prime
G1 Z0.2 F3000 ; get ready to prime
G92 E0 ; reset extrusion distance
G1 Y80 E10 F600 ; prime nozzle
G1 Y100 F5000 ; quick wipe

Any idea?

**Comment by ZONESTAR3D** [comment]
Pleas upload the newest firmware and try again, thanks!
